version: '2'
services:
  elasticsearch:
    image: elasticsearch:6.8.0
    env_file: .env
    ports:
      - 9200:9200
      - 9300:9300

  opendistro:
    image: amazon/opendistro-for-elasticsearch:1.12.0
    env_file: .env
    ports:
      - 19200:9200
      - 19300:9300

  opendistro_13:
    image: amazon/opendistro-for-elasticsearch:1.13.0
    env_file: .env
    ports:
      - 29200:9200
      - 29300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.0
    env_file: .env
    ports:
      - 5601:5601

